const { withAndroidManifest, withDangerousMod } = require('expo/config-plugins');
const fs = require('fs');
const path = require('path');

const DEFAULT_CONFIG_PATH = './backup_exclusions';

/**
 * Parse backup_exclusions file: newline-separated paths, # for comments.
 * Returns array of trimmed non-empty paths.
 */
function parseBackupExclusions(content) {
  return content
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line && !line.startsWith('#'));
}

/**
 * Read and parse the backup exclusions config file.
 */
function readConfig(projectRoot, configPath) {
  const resolved = path.resolve(projectRoot, configPath || DEFAULT_CONFIG_PATH);
  if (!fs.existsSync(resolved)) {
    throw new Error(
      `[expo-backup-exclusions] Config file not found: ${resolved}. ` +
        `Create it or set configPath in the plugin options.`
    );
  }
  const content = fs.readFileSync(resolved, 'utf8');
  const paths = parseBackupExclusions(content);
  if (paths.length === 0) {
    throw new Error(
      `[expo-backup-exclusions] No paths found in ${resolved}. ` +
        `Add paths (one per line) to exclude from cloud backups.`
    );
  }
  return paths;
}

function withBackupExclusions(config, options = {}) {
  let paths;

  // --- Android: generate XML and modify manifest ---
  config = withDangerousMod(config, [
    'android',
    async (config) => {
      const projectRoot = path.dirname(config.modRequest.platformProjectRoot);

      try {
        paths = readConfig(projectRoot, options.configPath);
      } catch (e) {
        console.warn(e.message);
        return config;
      }
      const resXmlDir = path.join(
        config.modRequest.platformProjectRoot,
        'app',
        'src',
        'main',
        'res',
        'xml'
      );

      if (!fs.existsSync(resXmlDir)) {
        fs.mkdirSync(resXmlDir, { recursive: true });
      }

      const excludeLines = paths
        .map((p) => `    <exclude domain="file" path="${p}"/>`)
        .join('\n');

      const fullBackupContent = `<?xml version="1.0" encoding="utf-8"?>
<full-backup-content>
${excludeLines}
</full-backup-content>
`;

      const dataExtractionRules = `<?xml version="1.0" encoding="utf-8"?>
<data-extraction-rules>
  <cloud-backup>
${excludeLines}
  </cloud-backup>
  <device-transfer>
${excludeLines}
  </device-transfer>
</data-extraction-rules>
`;

      fs.writeFileSync(
        path.join(resXmlDir, 'full_backup_content.xml'),
        fullBackupContent,
        'utf8'
      );
      fs.writeFileSync(
        path.join(resXmlDir, 'data_extraction_rules.xml'),
        dataExtractionRules,
        'utf8'
      );

      return config;
    },
  ]);

  config = withAndroidManifest(config, async (config) => {
    const manifest = config.modResults;
    const application = manifest.manifest.application?.[0];

    if (application) {
      application.$['android:fullBackupContent'] = '@xml/full_backup_content';
      application.$['android:dataExtractionRules'] =
        '@xml/data_extraction_rules';
    }

    return config;
  });

  // --- iOS: generate ExcludedPaths.generated.swift in the module ---
  config = withDangerousMod(config, [
    'ios',
    async (config) => {
      const projectRoot = path.dirname(config.modRequest.platformProjectRoot);

      let iosPaths;
      try {
        iosPaths = readConfig(projectRoot, options.configPath);
      } catch (e) {
        console.warn(e.message);
        return config;
      }

      const moduleIosDir = path.join(
        projectRoot,
        'modules',
        'expo-backup-exclusions',
        'ios'
      );

      if (!fs.existsSync(moduleIosDir)) {
        console.warn(
          '[expo-backup-exclusions] Module ios dir not found, skipping generated file'
        );
        return config;
      }

      const pathsLiteral = iosPaths.map((p) => `"${p}"`).join(', ');
      const generatedSwift = `// Auto-generated by expo-backup-exclusions config plugin. Do not edit.
import Foundation

enum ExcludedPaths {
    static let paths: [String] = [${pathsLiteral}]
}
`;

      fs.writeFileSync(
        path.join(moduleIosDir, 'ExcludedPaths.generated.swift'),
        generatedSwift,
        'utf8'
      );

      return config;
    },
  ]);

  return config;
}

module.exports = withBackupExclusions;
